"""Assemble the brand book from src/ parts.

Outputs
  index.html                     GitHub Pages page; links the two files below
  assets/css/brand-book.css      all page CSS (tokens, cover, book system)
  assets/js/brand-book.js        folio, reveals, save toggles, sample forms, copy buttons
  artifact.html                  single-file fragment for publishing as a Claude artifact
"""
import os, re
root = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
os.chdir(root)
read = lambda p: open(p, encoding='utf-8').read()

head = read('src/00-head.html')
head_html, head_css = head.split('<style>', 1)
book_css = read('src/10-book.css')
cover = read('src/20-cover.html')
book = read('src/30-book.html')
js_block = read('src/40-book.js')
js = re.sub(r'^\s*<script>\s*|\s*</script>\s*$', '', js_block)

# single-file artifact (the artifact host adds the doctype, head and body)
open('artifact.html', 'w', encoding='utf-8').write(head + book_css + '</style>' + cover + book + js_block)

# split files for GitHub Pages
os.makedirs('assets/css', exist_ok=True); os.makedirs('assets/js', exist_ok=True)
css = '/* The Oberdorfer Team — Brand Book No. 01. Generated by tools/build.py from src/00-head.html and src/10-book.css. */\n' + head_css + book_css
css = css.replace("url('assets/", "url('../")
open('assets/css/brand-book.css', 'w', encoding='utf-8').write(css)
open('assets/js/brand-book.js', 'w', encoding='utf-8').write('// Generated by tools/build.py from src/40-book.js.\n' + js.strip() + '\n')

page = ('<!doctype html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n'
        '<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">\n'
        '<style>:root{padding-top:env(safe-area-inset-top);padding-bottom:env(safe-area-inset-bottom)}body{margin:0}img{max-width:100%}[hidden]{display:none!important}</style>\n'
        + head_html.strip() + '\n'
        '<link rel="stylesheet" href="assets/css/brand-book.css">\n'
        '</head>\n<body>' + cover + book + '\n<script src="assets/js/brand-book.js"></script>\n</body>\n</html>\n')
open('index.html', 'w', encoding='utf-8').write(page)
for f in ('index.html', 'assets/css/brand-book.css', 'assets/js/brand-book.js', 'artifact.html'):
    print(f'{f}: {os.path.getsize(f):,} bytes')
