"""Sample content for the website concept.

Every listing here is illustrative: addresses, prices, taxes and stories are invented for the
demo and are labeled "Sample" wherever they appear. Photographs are credited Unsplash samples;
interiors in a listing gallery are not of that house.
"""

# Photographers, read from the provenance embedded in each file under assets/img/.
CREDIT = {
    '-yueOU_LlLw': 'Peyton Carroll', '0js8XJXFdtk': 'Austin', '0oj8ajN1PCY': 'Büsra Aksoy',
    '1CHyP92Oc04': 'I Do Nothing But Love', '28SK0CIr2Sg': 'Haberdoedas', '3Ns7li2szbU': 'LXS Photography',
    '4IE-NmsIwsA': 'Roger Starnes Sr', '5urBxoebDbQ': 'Clay Banks', '9sbTB3kLXBc': 'Nana Nakazwe',
    'AmF3jm4E_mg': 'Magic Fan', 'BAzT94876hk': 'Stuart Jenkins', 'BFEqlDN-UME': 'Nana Nakazwe',
    'Et-cTdVHF5U': 'Jessica Langbein', 'HKglFAYDMDE': 'Brett Wharton', 'MIKb6CuEcvw': 'Cam Fattahi',
    'MQE7ld8vxLI': 'Margo Evardson', 'PysSvRTfGyU': 'MV Vacation', 'Qjc6QtIEjjg': 'Omri D. Cohen',
    'S47fH1-Bk_s': 'Diane Helentjaris', 'Xr6P_KRQVFU': 'Hasnain Sikora', 'YHaw38vhcW0': 'Roger Starnes Sr',
    'eAXKQPELln4': 'LXS Photography', 'g_6zBGPST_4': 'Clay Banks', 'htmZWzApbJE': 'Clay Banks',
    'j5TewHOqdpw': 'Emi Mo', 'jDTQTylw3Bo': 'Roger Starnes Sr', 'lTVdmtPQCYU': 'Dominik Winter',
    'l_LRHud6NTA': 'Brett Wharton', 'ptRWMbqXNUo': 'Rick Lobs', 'r6uVcUq0I8E': 'Miguel Luis',
    'wT4w_U2424Q': 'Nana Nakazwe', 'S5gUvMmFKtk': 'Omri D. Cohen',
    }

# Pixel sizes, so every <img> carries width/height and the layout never jumps.
SIZE = {
    '-yueOU_LlLw': (1800, 1685), '0js8XJXFdtk': (1800, 1201), '0oj8ajN1PCY': (1200, 1800),
    '1CHyP92Oc04': (1800, 1195), '3Ns7li2szbU': (1800, 1634), '9sbTB3kLXBc': (1201, 1800),
    'AmF3jm4E_mg': (1350, 1800), 'BAzT94876hk': (1800, 1800), 'BFEqlDN-UME': (1800, 1201),
    'Et-cTdVHF5U': (1800, 1200), 'MIKb6CuEcvw': (1550, 1134), 'MQE7ld8vxLI': (1800, 1201),
    'PysSvRTfGyU': (1800, 1012), 'S47fH1-Bk_s': (1350, 1800), 'Xr6P_KRQVFU': (1001, 1800),
    'j5TewHOqdpw': (1800, 1192), 'l_LRHud6NTA': (1800, 1201), 'ptRWMbqXNUo': (1800, 1350),
    'r6uVcUq0I8E': (1136, 1800), 'wT4w_U2424Q': (1800, 1201),
    'Qjc6QtIEjjg': (1800, 1350), 'YHaw38vhcW0': (1800, 1192), 'DBbSEEwIFU0': (1800, 1013),
    'HKglFAYDMDE': (1800, 1350), 'eAXKQPELln4': (1800, 1673),
    '4IE-NmsIwsA': (1800, 853), 'jDTQTylw3Bo': (1800, 1192), 'lTVdmtPQCYU': (1800, 2700),
    'htmZWzApbJE': (1800, 1200), 'g_6zBGPST_4': (1800, 1195), '28SK0CIr2Sg': (1800, 1200),
    '5urBxoebDbQ': (1800, 1200), 'S5gUvMmFKtk': (1800, 1350),
}

# Interior samples used in listing galleries (never of the listed house; the gallery says so).
INTERIORS = [
    ('htmZWzApbJE', 'A kitchen with wood lower cabinets, open shelving and a wide window over the sink.', 'Kitchen'),
    ('g_6zBGPST_4', 'A living room with a black wood stove, wide wood floors and a braided rug.', 'Living room'),
    ('28SK0CIr2Sg', 'A bedroom with two tall casement windows and dark ceiling beams.', 'Bedroom'),
    ('5urBxoebDbQ', 'A covered porch with white columns and two wooden chairs facing a lawn.', 'Porch'),
    ('AmF3jm4E_mg', 'A curved stair with a dark wood rail and white balusters against green walls.', 'Stair hall'),
    ('BAzT94876hk', 'A curved bay of tall windows throwing afternoon sun across a wood floor.', 'Bay window'),
    ('MQE7ld8vxLI', 'An empty room with two deep-set windows, rough plaster walls and a plank ceiling.', 'Upstairs room'),
    ('r6uVcUq0I8E', 'A bright corridor of tall windows over a wide-plank floor.', 'Hall'),
]

TOWNS = ['Auburn', 'Boylston', 'Grafton', 'Holden', 'Northborough', 'Princeton', 'Shrewsbury', 'Westborough', 'Worcester']

# Illustrative map positions (percent of the map box), roughly east-west / north-south, not to scale.
TOWN_XY = {
    'Princeton': (17, 14), 'Holden': (30, 30), 'Boylston': (60, 24), 'Worcester': (40, 53),
    'Shrewsbury': (60, 50), 'Northborough': (81, 42), 'Westborough': (83, 63), 'Grafton': (66, 74),
    'Auburn': (33, 79),
}

# Where each town's name prints on the search map, clear of the price markers.
TOWN_LABEL_XY = {
    'Princeton': (17, 17), 'Holden': (24, 34), 'Boylston': (60, 27), 'Worcester': (31, 58),
    'Shrewsbury': (63, 49), 'Northborough': (82, 45), 'Westborough': (84, 66), 'Grafton': (65, 78),
    'Auburn': (32, 82),
}

LISTINGS = [
    dict(id='holden-14-orchard-lane', street='14 Orchard Lane', town='Holden', kind='Single family',
         price=689000, beds=4, baths='2.5', sqft=2140, lot='0.52 ac', year='c. 1780', style='Center chimney',
         heat='Oil, radiators', taxes='$8,912', own=True, open_house='Sun Oct 18, 11–1',
         photo='ptRWMbqXNUo', pos='50% 65%',
         alt='Front of a blue center-chimney colonial with yellow shutters, a small entry porch and granite steps.',
         character='Circa 1780 center-chimney colonial: wide pine floors, six-over-six windows, a 2019 kitchen in the old ell.',
         story=['The house was built around a single great chimney, with a parlor and a hall on either side and the kitchen behind. The wide pine boards in the front rooms are original; the 2019 renovation moved the kitchen into the old ell and left the frame exposed.',
                'Upstairs, four bedrooms open off a narrow center hall under the ridge. The back lot is level for about a hundred feet before it drops to a stone wall and the old orchard the street is named for.'],
         pins=(29, 27), gallery=[0, 1, 2, 4, 6]),
    dict(id='princeton-7-linden-street', street='7 Linden Street', town='Princeton', kind='Single family',
         price=825000, beds=5, baths='3', sqft=2980, lot='1.10 ac', year='1894', style='Shingle Style',
         heat='Gas, forced air', taxes='$11,240', own=True,
         photo='l_LRHud6NTA', pos='50% 55%',
         alt='A gray-shingled Queen Anne house with gables, a balcony and a cream picket fence.',
         character='Shingle Style, 1894: a wraparound balcony, the original stair and a turret room over the porch.',
         story=['Gray shingles over a stone base, three gables and a balcony that wraps the second floor on two sides. The stair is original, with a landing window that takes the morning light.',
                'The kitchen was opened to the old pantry in the 1990s and is due for its next renovation; the price reflects that.'],
         pins=(17, 11), gallery=[4, 5, 1, 2, 3]),
    dict(id='shrewsbury-31-maple-avenue', street='31 Maple Avenue', town='Shrewsbury', kind='Single family',
         price=749000, beds=4, baths='2.5', sqft=2410, lot='0.38 ac', year='1932', style='Colonial Revival',
         heat='Gas, hot water', taxes='$7,604', own=True, open_house='Sat Oct 17, 1–3',
         photo='1CHyP92Oc04', pos='22% 62%',
         alt='A white two-story colonial with black shutters and an enclosed front porch, behind a clipped hedge under a spring maple.',
         character='Colonial Revival, 1932: a fanlight gable, a heated sunroom and the original built-ins in the dining room.',
         story=['A symmetrical front, black shutters and an enclosed porch that the current owners use as a mudroom in winter and a reading room the rest of the year.',
                'The dining room keeps its corner cupboards. The sunroom on the south side was added in the 1960s and insulated in 2021.'],
         pins=(60, 44), gallery=[1, 0, 3, 2, 7]),
    dict(id='boylston-5-stone-row', street='5 Stone Row', town='Boylston', kind='Single family',
         price=559000, beds=3, baths='2', sqft=1760, lot='0.71 ac', year='1948', style='Gambrel',
         heat='Oil, baseboard', taxes='$6,318', own=True,
         photo='3Ns7li2szbU', pos='50% 45%',
         alt='A shingled gambrel-roof house with a glassed-in front porch above a dry-laid stone wall and spring plantings.',
         character='A 1948 gambrel above a dry-laid wall: an enclosed porch, three bedrooms under the roof, a level garden.',
         story=['The gambrel roof gives the second floor nearly full-height rooms, and the glassed porch faces south over the wall and the road.',
                'The garden is level and fenced at the back. The oil tank was replaced in 2018; the septic system will need its Title 5 inspection before sale.'],
         pins=(59, 20), gallery=[3, 1, 2, 0, 6]),
    dict(id='worcester-220-pleasant-street-unit-2', street='220 Pleasant Street, Unit 2', town='Worcester', area='West Side',
         kind='Condominium', price=365000, beds=2, baths='1', sqft=1050, lot='—', year='1910', style='Two-family conversion',
         heat='Gas, forced air', taxes='$3,880', own=False,
         photo='j5TewHOqdpw', pos='20% 50%',
         alt='Weathered shingle and clapboard houses in a row along a sunny street, long shadows across the sidewalk.',
         character='Second-floor unit in a 1910 two-family: bay windows to the street, a back porch, one deeded parking space.',
         story=['A second-floor unit in a converted two-family, with the front bay over the street and a back porch above the shared yard.',
                'Listed by another brokerage and shown here through the IDX feed with that brokerage credited.'],
         pins=(35, 49), gallery=[7, 2, 0, 1, 5]),
    dict(id='shrewsbury-18-church-road', street='18 Church Road', town='Shrewsbury', kind='Single family',
         price=679000, beds=4, baths='2', sqft=2060, lot='0.64 ac', year='1838', style='Farmhouse colonial',
         heat='Oil, hot water', taxes='$7,112', own=True,
         photo='YHaw38vhcW0', pos='50% 55%',
         alt='A white side-gabled farmhouse with black shutters, two chimneys and a small center portico behind a split-rail fence.',
         character='An 1838 side-gabled farmhouse: a center portico, two chimneys and a split-rail fence along the road.',
         story=['Two rooms on either side of a center stair, as built, with a long kitchen added across the back in the 1950s.',
                'The windows are later replacements; the floors and the front door are original. The barn foundation behind the house is all that remains of the outbuildings.'],
         pins=(68, 55), gallery=[0, 1, 4, 2, 3]),
    dict(id='northborough-26-elm-court', street='26 Elm Court', town='Northborough', kind='Single family',
         price=579000, beds=3, baths='2', sqft=1620, lot='0.29 ac', year='1928', style='Shingled bungalow',
         heat='Gas, hot water', taxes='$6,740', own=False,
         photo='Qjc6QtIEjjg', pos='55% 60%',
         alt='A gray-shingled cottage with white trim, a front porch and blue hydrangeas under a large tree.',
         character='A 1928 shingled cottage: a deep front porch, hydrangeas along the walk, and a garage at the end of the drive.',
         story=['Shingled walls, white trim and a cross gable over a deep porch. The hydrangeas along the walk are decades old.',
                'Listed by another brokerage and shown here through the IDX feed with that brokerage credited.'],
         pins=(81, 38), gallery=[3, 0, 2, 1, 5]),
    dict(id='westborough-3-brook-lane', street='3 Brook Lane', town='Westborough', kind='Single family',
         price=645000, beds=4, baths='2', sqft=2050, lot='0.46 ac', year='1948', style='Cape',
         heat='Gas, forced air', taxes='$8,020', own=True,
         photo='eAXKQPELln4', pos='40% 62%',
         alt='A white Cape with three dormers and an attached garage, behind clipped shrubs under a large tree.',
         character='A 1948 Cape with three dormers, an attached garage and a 1990s family room behind the kitchen.',
         story=['Dormers across the front give the upstairs two good bedrooms; two more are on the first floor.',
                'The family room behind the kitchen was added in the 1990s and opens to the back yard through French doors.'],
         pins=(84, 60), gallery=[0, 2, 1, 3, 6]),
    dict(id='auburn-15-fairview-avenue', street='15 Fairview Avenue', town='Auburn', kind='Single family',
         price=489000, beds=3, baths='1.5', sqft=1540, lot='0.33 ac', year='1972', style='Raised ranch',
         heat='Oil, baseboard', taxes='$5,610', own=False,
         photo='4IE-NmsIwsA', pos='50% 60%',
         alt='A brown-shingled raised ranch with a brick lower level, shrubs along the front and a wide lawn.',
         character='A 1972 raised ranch: three bedrooms on the main level and a finished lower level with its own entrance.',
         story=['A split-entry plan: living, kitchen and three bedrooms up; a family room, half bath and laundry down.',
                'Listed by another brokerage and shown here through the IDX feed with that brokerage credited.'],
         pins=(32, 76), gallery=[0, 1, 2, 7, 3]),
    dict(id='worcester-41-elmwood-terrace', street='41 Elmwood Terrace', town='Worcester', area='West Side',
         kind='Single family', price=719000, beds=5, baths='2.5', sqft=2860, lot='0.22 ac', year='1898', style='Queen Anne',
         heat='Gas, radiators', taxes='$8,450', own=True,
         photo='jDTQTylw3Bo', pos='50% 50%',
         alt='A blue Queen Anne house with white trim, a turned-post wraparound porch and a decorated front gable.',
         character='An 1898 Queen Anne with a wraparound porch, pocket doors and the original radiators throughout.',
         story=['A wraparound porch on turned posts, a decorated front gable and a hall that runs straight through to the kitchen.',
                'The parlors still have their pocket doors. The radiators are original and were rebalanced when the boiler was replaced in 2020.'],
         pins=(45, 59), gallery=[4, 1, 5, 2, 0]),
    dict(id='grafton-9-common-way', street='9 Common Way', town='Grafton', kind='Single family',
         price=869000, beds=4, baths='3', sqft=2720, lot='0.48 ac', year='c. 1790', style='Federal',
         heat='Oil, hot water', taxes='$10,310', own=True,
         photo='Et-cTdVHF5U', pos='38% 50%',
         alt='A barn-red clapboard colonial with pedimented window heads and dormers, above a brick sidewalk.',
         character='A Federal house of about 1790: pedimented window heads, three dormers and a brick walk to the street.',
         story=['Barn-red clapboards, pedimented window heads and a center entry. The dormers were added in the nineteenth century to light the attic bedrooms.',
                'Two of the fireplaces work; the others were closed when the house was converted to hot-water heat.'],
         pins=(65, 71), gallery=[6, 4, 0, 1, 2]),
]

FEATURED = 'holden-14-orchard-lane'
HOME_COMPACT = ['shrewsbury-31-maple-avenue', 'worcester-41-elmwood-terrace']

ARTICLES = [
    dict(slug='old-house-checklist', href='field-notes/old-house-checklist.html', kind='Guides', length='8 min',
         title='What to check before you fall for an old house',
         dek='Sills, chimneys, wiring, oil tanks and septic: the questions that are cheaper to ask before an offer than after it.',
         photo='MQE7ld8vxLI', alt='An empty old room with two deep-set windows, rough plaster walls and a plank ceiling.'),
    dict(slug='shrewsbury', href='shrewsbury.html', kind='Town guides', length='Town page',
         title='Shrewsbury, from the lake to Route 9',
         dek='Lake Quinsigamond on one side, Route 9 through the middle, and the town center on the hill between them.',
         photo='0js8XJXFdtk', alt='A cut-granite building with a pedimented blue door, black railings and a maple turning orange.', pos='50% 62%'),
    dict(slug='orchard-lane', href='homes/holden-14-orchard-lane.html', kind='House stories', length='Sample listing',
         title='The house on Orchard Lane',
         dek='A center-chimney colonial, a kitchen moved into the ell, and why the floors were left alone.',
         photo='ptRWMbqXNUo', alt='Front of a blue center-chimney colonial with yellow shutters.'),
    dict(slug='market-fall', href=None, kind='Market', length='Monthly',
         title='Worcester County this fall, in plain numbers',
         dek='Median price, days on market and inventory, explained. Figures arrive from MLS PIN when the feed is connected.',
         photo='BFEqlDN-UME', alt='Red brick commercial buildings with mansard roofs above a downtown Worcester intersection.'),
    dict(slug='first-winter', href=None, kind='Guides', length='5 min',
         title='Your first winter in a New England house',
         dek='Heat, ice dams, storm windows and the maintenance calendar nobody hands you at the closing.',
         photo='0oj8ajN1PCY', alt='Late sun falling through an old wooden interior shutter in a deep green window reveal.', pos='50% 42%'),
    dict(slug='title-5', href=None, kind='Guides', length='6 min',
         title='Title 5, explained before you need it',
         dek='What the septic inspection checks, who orders it, and what happens to a sale when a system fails.',
         photo='S47fH1-Bk_s', alt='A white six-over-six window set into barn-red clapboard above a fieldstone foundation.', pos='50% 35%'),
]
